# Generated by Django 3.0 on 2020-03-04 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date time')),
                ('status', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(10)])),
                ('currency', models.CharField(max_length=3)),
                ('saved', models.BooleanField()),
            ],
        ),
    ]
