# Generated by Django 3.0 on 2020-03-04 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jambhala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancel_wait',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_vk',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_mailed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last sended email date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_pay_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='next_pay',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Next payment date time for saved paymemts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='note_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note_subj',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_ref',
            field=models.CharField(default='asdf', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='pid',
            field=models.CharField(default='afa', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='short_bank_info',
            field=models.CharField(default='none bank', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date time'),
        ),
    ]
