# Generated by Django 3.0 on 2019-12-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=35)),
                ('long_name', models.CharField(max_length=108)),
                ('is_hural', models.BooleanField(default=True)),
                ('celebration_hural', models.BooleanField(default=False)),
                ('for_best_reincarnation', models.BooleanField(default=False)),
                ('note_allowed', models.BooleanField(default=True)),
                ('note_for_one_name', models.BooleanField(default=False)),
                ('note_fix_price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoonDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day_no', models.IntegerField()),
                ('_moon_day_no', models.IntegerField(db_column='moon_day_no')),
                ('refuge', models.BooleanField(default=False)),
                ('pujah', models.BooleanField(default=False)),
                ('mandala_destruction', models.BooleanField(default=False)),
                ('lusuud', models.BooleanField(default=False)),
                ('tsetar', models.BooleanField(default=False)),
                ('baldjinima', models.BooleanField(default=False)),
                ('dashinima', models.BooleanField(default=False)),
                ('tersuud', models.BooleanField(default=False)),
                ('modon_hohimoy', models.BooleanField(default=False)),
                ('riha', models.BooleanField(default=False)),
                ('pagshag', models.BooleanField(default=False)),
                ('good_for_haircut', models.BooleanField(default=False)),
                ('good_for_travel', models.BooleanField(default=False)),
                ('significant_day', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('lamas_checked', models.BooleanField(default=False)),
                ('day_hural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day2ritual', to='mooncal.Ritual')),
                ('morning_hural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning2ritual', to='mooncal.Ritual')),
                ('night_hural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='night2ritual', to='mooncal.Ritual')),
            ],
        ),
    ]
