# Generated by Django 3.0 on 2019-12-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraswati', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moonday',
            name='_moon_day_no',
        ),
        migrations.AddField(
            model_name='moonday',
            name='moon_day_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
