# Generated by Django 3.0 on 2020-02-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saraswati', '0002_auto_20191216_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moonday',
            name='lusuud',
        ),
        migrations.RemoveField(
            model_name='moonday',
            name='mandala_destruction',
        ),
        migrations.RemoveField(
            model_name='moonday',
            name='night_hural',
        ),
        migrations.RemoveField(
            model_name='moonday',
            name='pujah',
        ),
        migrations.RemoveField(
            model_name='moonday',
            name='refuge',
        ),
        migrations.RemoveField(
            model_name='moonday',
            name='tsetar',
        ),
        migrations.AlterField(
            model_name='moonday',
            name='day_hural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day2ritual', to='saraswati.Ritual'),
        ),
        migrations.AlterField(
            model_name='moonday',
            name='morning_hural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning2ritual', to='saraswati.Ritual'),
        ),
    ]
