# Generated by Django 3.0 on 2020-02-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooncal', '0003_auto_20200223_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('ritual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event2ritual', to='mooncal.Ritual')),
            ],
        ),
    ]
