# Generated by Django 3.0 on 2020-02-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooncal', '0006_auto_20200226_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moonday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='mooncal.MoonDay'),
        ),
    ]
