# Generated by Django 3.0 on 2020-02-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooncal', '0008_auto_20200226_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ritual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mooncal.Ritual'),
        ),
    ]
