# Generated by Django 3.0 on 2020-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraswati', '0009_auto_20200226_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ritual',
            new_name='ritual_id',
        ),
        migrations.AlterField(
            model_name='ritual',
            name='long_name',
            field=models.TextField(max_length=108),
        ),
    ]
